"""Auth for apps/workers' HTTP endpoints. Two different mechanisms for two
different kinds of caller — neither is apps/api's per-user JWT login:

- Agent triggers (`/agents/*`) are called server-to-server, from apps/api's
  proxy routes (see apps/api/src/workersClient.ts) — `require_workers_token`
  checks a single shared secret (`WORKERS_API_TOKEN`).
- Telemetry ingestion (`/ingestion/*`) is called by devices, which don't log
  in as a user and don't share apps/api's secret either — `check_device_auth`
  checks a per-device key instead (Device.apiKeyHash, generated by apps/api
  when the device is created — see apps/api/src/apiKeys.ts). A device with
  no key configured falls back to WORKERS_API_TOKEN, so seeded/demo devices
  (which never got a key) keep working without extra setup.

Both fall open (no check) if their governing secret is unset — deliberate
for local dev, matching the `ANTHROPIC_API_KEY` convention. Left unset,
those endpoints are open; see CLAUDE.md.
"""

from __future__ import annotations

import hashlib
import os
from typing import Optional

from fastapi import Header, HTTPException
from sqlalchemy import select

from app.db import devices, get_engine


def _extract_bearer(authorization: Optional[str]) -> Optional[str]:
    if authorization and authorization.startswith("Bearer "):
        return authorization[len("Bearer ") :]
    return None


async def require_workers_token(authorization: Optional[str] = Header(default=None)) -> None:
    expected = os.environ.get("WORKERS_API_TOKEN")
    if not expected:
        return

    if _extract_bearer(authorization) != expected:
        raise HTTPException(status_code=401, detail="Missing or invalid bearer token")


async def check_device_auth(device_id: str, authorization: Optional[str] = Header(default=None)) -> None:
    engine = get_engine()
    async with engine.connect() as conn:
        row = (
            await conn.execute(
                select(devices.c.api_key_hash).where(
                    devices.c.id == device_id, devices.c.deleted_at.is_(None)
                )
            )
        ).first()

    if row is None:
        # Unknown (or soft-deleted) device — let the ingestion handler's own
        # lookup produce the clean "unknown_device" response rather than
        # failing auth first.
        return

    token = _extract_bearer(authorization)

    if row.api_key_hash:
        if token is None or hashlib.sha256(token.encode()).hexdigest() != row.api_key_hash:
            raise HTTPException(status_code=401, detail="Missing or invalid device API key")
        return

    expected = os.environ.get("WORKERS_API_TOKEN")
    if expected and token != expected:
        raise HTTPException(status_code=401, detail="Missing or invalid bearer token")
